apiVersion: 1

datasources:
  - name: SmartHospitalDB
    type: mysql
    url: mysql:3306
    database: smart_hospital
    user: hospital_user
    secureJsonData:
      password: hospital_pass_2024
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      tlsAuth: false
      tlsAuthWithCACert: false
    isDefault: true
    editable: false
