apiVersion: 1

datasources:
  - name: SmartHospitalDB
    type: postgres
    url: postgres:5432
    database: smart_hospital
    user: hospital_user
    secureJsonData:
      password: hospital_pass_2024
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600
      sslmode: disable
    isDefault: true
    editable: false
